---
title: "Week 3 Assignment"
author: "Xavier Aguiar"
date: "6/9/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r prerquisites}
rm(list=ls())
library(plotly)
library(data.table)
library(tidyr)
library(lubridate)
library(zoo)
install.packages("zoo")
```

```{r setting variables}
accidents0514 <- read.csv("accidents.csv", header = TRUE, 
                 sep = ",")

accidents0514 <- accidents0514 %>% select(Accident_Severity, Date)

accidents15 <- read.csv("accident15.csv", header = TRUE, 
                     sep = ",")

accidents15 <- accidents15 %>%
  select(Casualty.Severity, Accident.Date)





colnames(accidents15)[2] <- "Date"
colnames(accidents15)[1] <- "Accident_Severity"



# concatenate data tables and free up environment
accidents <- rbind(accidents0514, accidents15)
rm(list = c("accidents0514", "accidents15"))
```

```{r process_data}
# convert severity to factor and add labels
accidents$Accident_Severity <- 
  factor(accidents$Accident_Severity, 
         levels = 1:3, labels = c("Fatal", "Serious", "Slight"))

# convert date strings to Date objects
accidents$Date <- dmy(accidents$Date)


# group data by date and severity, get count, one row per date
accident_count <- accidents
accident_count %>% 
  group_by(Date, Accident_Severity) %>%
  summarise(count = n() %>%
  spread(key = Accident_Severity, value = count) %>% 
  as.data.frame(accidents) 
  
loess_slight <- loess(Slight ~ as.numeric(Date), 
                      data = accident_count)
loess_serious <- loess(Serious ~ as.numeric(Date), 
                       data = accident_count)
loess_fatal <- loess(Fatal ~ as.numeric(Date), 
                     data = accident_count)
```
## Road accidents in GB (2005-2015)

```{r plot}
# plot data
plot_ly(accident_count)

```


